### PR TITLE
add draft of 2 surveys

### PR DESCRIPTION
**Pull request by konradpa**
add first drafts of CLI and git basics surveys, open to feedback.

Feedback section not solved optimally.

### CODE REVIEW

**Comment by lnnrtwttkhn** [comment]
thanks @konradpa, looks good! made a few minor fixes (see commits above).

could you please do the following
1. on formr.org create new surveys for all our surveys listed in `_sheets.yml` using the following pattern: `version-control-<name>`, for example `version-control-cli` (please remember to use lower caps and hyphens `-`).
1. please update all the google sheets links in `_sheets.yml` in the corresponding surveys on formr.org
1. load the items and test all the surveys: check if the current items render correctly etc. and note anything that you think is still missing either in this PR or a new issue.

then we can later go over all open points together and eventually merge. thank you!

**Comment by konradpa** [comment]
```r
Error in file(file, "rt", encoding = fileEncoding) : 
  invalid 'description' argument
Calls: df2google ... write_sheet -> eval_tidy -> yml2df -> <Anonymous> -> file
Execution halted
make: *** [installation] Error 1
```

@lnnrtwttkhn add `surveys/installation.yml` please!

**Comment by lnnrtwttkhn** [comment]
> @lnnrtwttkhn add `surveys/installation.yml` please!

done! see https://github.com/lnnrtwttkhn/version-control-survey/commit/5b5383c8603e6dc12b47b346d329a59f39faae6d

**Comment by konradpa** [comment]
@lnnrtwttkhn 
fixed/added some minor stuff (see commits) looks good to merge to me

**Pull request merged**
